on: [push]

jobs:
  hello_world_job:
  runs-on: ubuntu-latest
  name: A job to say hello
  steps:
    - uses: actions/checkpout@v4
    - id: foo
      uses: umair-2707/GA-customejs@v1
      with: 
        who-to-greet: 'Mona the Octocat'
    - run: echo random-number "$RANDOM NUMBER"
      shell: bash
      env: 
        RANDOM_NUMBER: ${{ step.foo.outputs.random-number }}
        
      
